#server.port=8080
#management.endpoints.web.exposure.include=*

server:
  port: 8080

spring:
  application:
    name: monitoring
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS